export const UPDATE_CUISINE = 'UPDATE_CUISINE';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_OTHERCATEGORY = 'UPDATE_OTHERCATEGORY';
export const UPDATE_COST = 'UPDATE_COST';
export const UPDATE_RATING = 'UPDATE_RATING';
export const UPDATE_LIST = 'UPDATE_LIST';
export const LOAD_MORE = 'LOAD_MORE';
export const LOADING = 'LOADING';
